### ISSUE TITLE
1.16.5 Crash between Tetra Tetronomicon and Apotheosis

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Syrikal/Tetranomicon#1]
# Crash Log
https://gist.github.com/P3rf3ctXZer0/26fc1f73ab7bb92c9fa6d6d8bdb21c58

# Latest Log
https://gist.github.com/P3rf3ctXZer0/257d17f90763319fefa1ead17001e849

# Forge 
36.0.42

# Mod Version
mgui-1.16.4-3.1.3
tetra-1.16.4-3.6.1
tetranomicon-1.0

**Comment by P3rf3ctXZer0** [comment]
I will work on narrowing it down.

**Comment by P3rf3ctXZer0** [comment]
Related to Apotheosis 

![eIyzyl1 1](https://user-images.githubusercontent.com/10351221/108516957-6fb43100-728c-11eb-96a0-9a8152e0dc35.png)

**Comment by P3rf3ctXZer0** [comment]
# Crash Log After Being Narrowed Down
https://gist.github.com/P3rf3ctXZer0/c69a20584eac6bc539251e6a6ef724b1

**Comment by P3rf3ctXZer0** [comment]
# Build: 1.16.5-36.0.41 - Tue Feb 16 01:28:51 GMT 2021
	knightminer4:
		Fix updateItemStackNBT not properly being called (#7646)
		
		Re-added ItemStack delegate redirect transformer
		
		
Directly related to forge changes. The crash is known in the tetra community.

**Comment by Syrikal** [comment]
Does this happen when you remove Tetranomicon? All this note does is load a data pack, do i can't imagine why it would cause a crash.

**Comment by P3rf3ctXZer0** [comment]
It seems its an issue with forge. So I don't think you can fix it at this time.
