### ISSUE TITLE
Canopy and Twilight Oak Are Mislabled, Swapped.

### ISSUE THREAD

**Issue by ghost** [Syrikal/Tetranomicon#10]
The offending code sections are I believe in the json files linked [here](https://github.com/Syrikal/Tetranomicon/blob/main/src/main/resources/data/tetra/materials/wood/canopy.json) and [here](https://github.com/Syrikal/Tetranomicon/blob/main/src/main/resources/data/tetra/materials/wood/twilightoak.json). I'm not sure which one's which though so here's an open ticket instead of a merge request.
## Here are some screenshots:
![Canopy as Twilight Oak](https://user-images.githubusercontent.com/78946243/147542509-174cec67-047f-466b-a509-313594b79606.png)
![Twilight Oak as Canopy](https://user-images.githubusercontent.com/78946243/147542510-9a3ff9b9-bf39-4683-bc49-7e1e73a6076c.png)

**Comment by Syrikal** [comment]
Fixed this a while back and forgot to close the issue.
