### ISSUE TITLE
Twilight Forest Innate Enchantments Not Applied

### ISSUE THREAD

**Issue by annastropha** [Syrikal/Tetranomicon#15]
tetranomicon-1.4.2-1.19.2  
tetra-1.19.2-5.2.1  

As the title - the traits don't actually apply the enchantment effects. Tested with Steelleaf's fortune, as I wanted to copy it to Gold for a pack and it was not working.

**Comment by Syrikal** [comment]
Unfortunately Tetra doesn't support this in 1.18 or 1.19. I'll re-add it once it does.

**Comment by Syrikal** [comment]
Tetra supports this again in 1.20 and these effects are working again in all 1.20 versions of Tetranomicon.
