### ISSUE TITLE
Crash from unintended dependency with Stalwart Dungeons?

### ISSUE THREAD

**Issue by andrewszidon** [Syrikal/Tetranomicon#18]
When I tried opening a world it crashed. The error said something about stalwart_dungeons:tungsten_hoe, so I tried getting Stalwart Dungeons, and then it worked. I also tried turning off both Stalwart Dungeons and Tetranomicon, and it worked. I saw in Relations that Stalwart Dungeons was listed as an Optional Dependency, so I'm guessing this was unintentional?

(1.20.1 btw)

**Comment by Syrikal** [comment]
Does this happen with _only_ Tetranomicon (and its required dependencies, Tetra and mutil) installed? If not, what other mods need to be present for this to happen?

**Comment by andrewszidon** [comment]
Ah. It seems that just Tetronomicon (plus dependencies) doesn't cause the crash. The crash on world creation only starts happening when there's both Tetronomicon and Enderite.

Enderite=no crash
Tetranomicon=no crash
Enderite+Tetranomicon=crash
Enderite+Tetranomicon+Stalwart Dungeons=crash
Enderite+Tetranomicon+Stalwart Twilight Forest=crash
Enderite+Tetranomicon+Stalwart Dungeons+Twilight Forest=no crash
Tetranomicon+Stalwart Dungeons+Twilight Forest=no crash
Stalwart Dungeons+Twilight Forest=no crash
Enderite+Twilight Forest=no crash
Enderite+Stalwart Dungeons=no crash

Btw when I had both Stalwart Dungeons and Tetranomicon toggled on, and I turned off Stalwart Dungeon, the CurseForge launcher automatically turned off Tetranomicon.

**Comment by Syrikal** [comment]
That's amazing, thanks!

I've got it figured out now - the dependencies are tangled a little, so if Enderite is present Tetranomicon tries to load Stalwart and Twilight content instead of checking whether they're present independently. I'll upload a fixed version tonight.
