### ISSUE TITLE
Nether Star socket appears as a diamond socket, has no localization, etc.

### ISSUE THREAD

**Issue by MindFaer** [Syrikal/Tetranomicon#2]
The Nether Star socket has is identical to a regular diamond socket in every way, including showing up as one when looking at what is on the item, when comparing stats to a diamond socket, when comparing texture, and so on. The only differences are that the nether star socket takes 30 exp levels to place into the socket, and the diamond takes two, and the diamond takes 2 exp levels, and the name for the diamond is "Socket [Diamond]", where as the nether star is shown in the holosphere as "tetra.variant.[tool name]/nether_star"
![2021-02-27_01 32 20](https://user-images.githubusercontent.com/75921990/109388305-4753b480-78d4-11eb-95cf-c8db40d536b7.png)
![2021-02-27_01 32 23](https://user-images.githubusercontent.com/75921990/109388306-49b60e80-78d4-11eb-8696-98b2209e7514.png)
![2021-02-27_01 38 17](https://user-images.githubusercontent.com/75921990/109388307-4b7fd200-78d4-11eb-97cf-f01c5fd42021.png)

**Comment by Syrikal** [comment]
Whoops. There used to be a Nether Star socket, but I removed it as unnecessary. Looks like I removed the module file, which would give it stats, but forgot to remove the schematic file, which allows it to be made. I'll fix this with the next update.

**Comment by Syrikal** [comment]
Fixed in 1.1.
