### ISSUE TITLE
Inconsistency with base tetra in 1.20.1 1.5 Alpha 1

### ISSUE THREAD

**Issue by Nemo-et-Nihil** [Syrikal/Tetranomicon#20]
Base Tetra (well Tetracelium technically now that mickelus moved the built in mod compatibility there) defines material stats for all metals tagged forge:silver. The alpha for 1.5 tetranomicon includes stats for the galosphere silver ingot, which is tagged forge:ingots/silver, and this reults in two seperate options for the same material being present. Maybe not a bug, but it is a bit redundant, plus the tetranomicon stats are slightly worse because there is no stabilizing bonus.
![tetranomicon1](https://github.com/Syrikal/Tetranomicon/assets/63416145/16d5fe84-236d-4de3-b206-9de305d9624b)

**Comment by Syrikal** [comment]
Fixed in 1.5.1.
