### ISSUE TITLE
Glinted amethyst socket has the wrong name for the attack range attribute 

### ISSUE THREAD

**Issue by Nemo-et-Nihil** [Syrikal/Tetranomicon#22]
The attribute should be "forge:attack_range, not "forge:attack_distance. Currently that aspect of ther socket does not work.
![image](https://github.com/Syrikal/Tetranomicon/assets/63416145/06fecb2d-ff8e-4783-94cf-c15e04b15701)

**Comment by Syrikal** [comment]
Fixed in 1.5.1.
