### ISSUE TITLE
Tetranomicon v1.5.1 for Minecraft 1.16.5 crashes on startup: Compiled for more recent runtime

### ISSUE THREAD

**Issue by Rsge** [Syrikal/Tetranomicon#24]
When using the new Tetranomicon v1.5.1 for Minecraft 1.16.5, the game crashes immediately after the first stage of loading.
The error shown in the `latest.log` is the following:
`java.lang.UnsupportedClassVersionError: com/syric/tetranomicon/Tetranomicon has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0`.

Tetranomicon v1.4 works without problems.

Using:
* CurseForge launcher
* Forge 36.2.34
* Java 1.8.0.391 64 Bit (set in CurseForge's settings)

I also tried the newest version of Java 11 (same result) and Java 17 (crashes because of incompatibility with MC 1.16.5).

Attachment:
* [latest.log](https://github.com/Syrikal/Tetranomicon/files/14195123/latest.log)

**Comment by Syrikal** [comment]
Fixed in 1.5.2, thanks for the tip!

**Comment by Rsge** [comment]
No problem and thank you very much for the fast fix.
I was just about to say I can't see the version on CF, but then realized you only answered 3 mins ago. Will try it probably tomorrow, it's 3 AM my time.

**Comment by Rsge** [comment]
It works now, *buuut* while the file name is `1.5.2 - 1.16.5`, the CurseForge version tag is `1.20.1`, so I had to download it manually to try it.
![image](https://github.com/Syrikal/Tetranomicon/assets/23245821/e1f75ec5-f811-443b-ae9a-836643f6acd4)

**Comment by Syrikal** [comment]
Oops! Also fixed a different mod for 1.20 and got the Curse tags swapped. Fixed now.
