### ISSUE TITLE
Tetranomicon v1.5.2 crashes on dedicated server: NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag

### ISSUE THREAD

**Issue by Rsge** [Syrikal/Tetranomicon#25]
When using the new Tetranomicon v1.5.2 on a Minecraft 1.16.5 **dedicated server**, it crashes shortly after starting.
The error shown in the `latest.log` is the following:
```
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Tetranomicon (tetranomicon) has failed to load correctly
?7java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
]
```

Tetranomicon v1.4 works without problems.

Attachment:
[latest.log](https://github.com/Syrikal/Tetranomicon/files/14230001/latest.log)

PS:
Sorry to bother again. Client works fine btw, thank you : )

**Comment by Syrikal** [comment]
...and that's what I get for rushing a fix. on it!

**Comment by Syrikal** [comment]
Alright, hopefully 1.5.3 should fix this, but the dev environment is being irritatingly obtuse about testing it. I've posted it to CurseForge. Give it a try when it goes public and let me know if it works for people other than me.

**Comment by Rsge** [comment]
v1.5.3 works like a charm on my dedicated server (or at least it loads and I can connect), so what you did seems to have worked.
Thanks again for fixing this so fast and have a nice day/night : )
