### ISSUE TITLE
Sculk Bone integrity is wrong

### ISSUE THREAD

**Issue by Devintrainer** [Syrikal/Tetranomicon#27]
When using sculk bone as a material, I noticed that its integrity usage is screwed up. The sculk bone hilt/handle only gives 2 integrity, while the sculk bone blade and spearhead uses up 8 integrity, making them both useless. What I definitely feel like is supposed to happen is that the hilt/handle gives 8 integrity while the blade/spearhead uses up 2 integrity. I wonder if any other materials have this issue as well, but I haven't really checked.

**Comment by Syrikal** [comment]
This is intentional behavior - sculk bone has an extremely high tool level. Its intended function is to be used to make a knife that can cut Sculk Vine.
