### ISSUE TITLE
Handle Wraps Missing?

### ISSUE THREAD

**Issue by uhhhhhhhhhhg** [Syrikal/Tetranomicon#3]
Can no longer use materials like string or leather to wrap the handle on tools. All previous handle wrappings disappeared after install.

Using the most up-to-date version of both mods.

**Before:**
![image](https://user-images.githubusercontent.com/66751838/113241115-43b4a400-926b-11eb-9f99-cf0d82661d6b.png)

**After:**
![image](https://user-images.githubusercontent.com/66751838/113240718-7a3def00-926a-11eb-9d5d-fc600be8ab99.png)

**Comment by Syrikal** [comment]
Uh oh, that's not good. I knew there was an overwriting issue, but the other reports I've received are of the default wraps overwriting the new ones, not the other way around!

Sorry this happened to you. I'll get a fix out ASAP.

**Comment by uhhhhhhhhhhg** [comment]
I should mention that the handle wrappings reappeared after I uninstalled the mod. Sorry I forgot to mention that.

**Comment by Syrikal** [comment]
That's a relief, at least. Releasing a fixed version (1.2) now.
