### ISSUE TITLE
Tier 8 Axe impossible?

### ISSUE THREAD

**Issue by Ru-Lo-Mo** [Syrikal/Tetranomicon#4]
Is there any way to make a tier 8 axe? I'm trying to make a dragon wood recurve bow with wyrmroost and betterend resources.

**Comment by Syrikal** [comment]
Purple Geode and Eternal Crystal are both Tier 7. You should be able to hone an axe to increase its tier by 1, after you hone its efficiency five times. This is definitely an end-game undertaking, but a dragon wood recurve bow is very powerful. Good luck!

**Comment by Ru-Lo-Mo** [comment]
Wow i though i would have to do some kind of witchcraft. I already knew of the tier upgrade in the hammer by increasing durability, it tried it on the axe too, but it didn't cross my mind that it could be a different atribute. Thanks for the hasty response!
