### ISSUE TITLE
Ice & Fire handle wraps

### ISSUE THREAD

**Issue by Royal-Jelly** [Syrikal/Tetranomicon#6]
Dragon scales and other Ice and fire handle wraps appear to be missing. Is this an unfinished feature?

**Comment by Syrikal** [comment]
This issue was present in 1.1 but should have been fixed in 1.2. Which version are you using?

**Comment by Royal-Jelly** [comment]
I'm on 1.2 now ... swore I updated, apparently not. Sorry about the duplicate issue, closing issue now.
