### ISSUE TITLE
How can I possibly get 9 tier hammer?

### ISSUE THREAD

**Issue by hamurci** [Syrikal/Tetranomicon#9]
I just wanted to make a powerful long bow with tetra using my icedragonsteel ingots from iceandfire mod today.But I realized that it needs 9 tier hammer available to make it. I am using tetra's underground hammer with 2 tier upgrade modules but it only gives me 7 tier.So,how can I possibly get 9 tier? I've tried to look config file and edit the requirement values but I couldn't even find config file of tetranomicon. help me pls

**Comment by Alphalilly** [comment]
same problem is there something im missing?
